{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "simpleshop.postgresName" . }}
  annotations:
    helm.sh/resource-policy: keep
  labels:
    {{- include "simpleshop.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.postgresql.storage }}
{{- end }}
