{{- if .Values.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "simpleshop.name" . }}
  labels:
    {{- include "simpleshop.labels" . | nindent 4 }}
type: Opaque
stringData:
  SESSION_SECRET: {{ .Values.sessionSecret | quote }}
  PGPASSWORD: {{ if .Values.postgresql.enabled }}{{ .Values.postgresql.password | quote }}{{ else }}{{ .Values.externalPostgresql.password | quote }}{{ end }}
{{- end }}
