apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: simpleshop-prod

helmGlobals:
  chartHome: ../../..

helmCharts:
  - name: helm
    releaseName: simpleshop
    valuesFile: values.yaml
    includeCRDs: true

secretGenerator:
  - name: simpleshop
    behavior: create
    options:
      disableNameSuffixHash: true
    envs:
      - secrets.env
